# Generated by Django 3.0.7 on 2020-07-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oaadmin',
            fields=[
                ('ldap', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ldap')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='姓名')),
            ],
            options={
                'verbose_name_plural': '管理员权限管理',
                'db_table': 'oaadmin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oaapprover',
            fields=[
                ('ldap', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ldap')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='姓名')),
                ('leave', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, max_length=255, null=True, verbose_name='能否审批请假')),
                ('dimission', models.CharField(choices=[(0, '否'), (1, '是')], default=0, max_length=255, null=True, verbose_name='能否审批离职权限')),
            ],
            options={
                'verbose_name_plural': '审批权限管理',
                'db_table': 'oaapprover',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oaexecutives',
            fields=[
                ('ldap', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='姓名')),
            ],
            options={
                'verbose_name_plural': '执行权限管理',
                'db_table': 'oaexecutives',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oafinance',
            fields=[
                ('ldap', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='姓名')),
            ],
            options={
                'verbose_name_plural': '财政权限管理',
                'db_table': 'oafinance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oahr',
            fields=[
                ('ldap', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='姓名')),
                ('company', models.CharField(max_length=255, null=True, verbose_name='可导出员工信息的公司名称')),
                ('exportstaff', models.CharField(choices=[(0, '否'), (1, '是')], db_column='exportStaff', default=0, max_length=255, null=True, verbose_name='能否导出员工')),
                ('confirmentry', models.CharField(choices=[(0, '否'), (1, '是')], db_column='confirmEntry', default=0, max_length=255, null=True, verbose_name='能否确定入职')),
                ('cancel_ack_leave_auth', models.CharField(choices=[(0, '否'), (1, '是')], default=0, max_length=255, null=True, verbose_name='能否销假')),
            ],
            options={
                'verbose_name_plural': '人事权限管理',
                'db_table': 'oahr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oaother',
            fields=[
                ('ldap', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名')),
                ('qr_code_auth', models.CharField(choices=[(0, '否'), (1, '是')], default=0, max_length=255, null=True, verbose_name='能否重置二维码')),
                ('password_auth', models.CharField(choices=[(0, '否'), (1, '是')], default=0, max_length=255, null=True, verbose_name='能否重置密码')),
                ('add_ldap_auth', models.CharField(choices=[(0, '否'), (1, '是')], default=0, max_length=255, null=True, verbose_name='能否添加ldap')),
            ],
            options={
                'verbose_name_plural': 'IT权限管理',
                'db_table': 'oaother',
                'managed': False,
            },
        ),
    ]
