# Generated by Django 3.0.7 on 2020-07-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oaexecutives',
            options={'managed': False, 'verbose_name_plural': 'HRBP管理'},
        ),
        migrations.AlterModelOptions(
            name='oafinance',
            options={'managed': False, 'verbose_name_plural': '财务权限管理'},
        ),
    ]
