# Generated by Django 3.0.7 on 2020-07-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0002_auto_20200710_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='OaPosition',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='职位名称')),
            ],
            options={
                'verbose_name_plural': '职位管理',
                'db_table': 'oa_position',
                'managed': False,
            },
        ),
    ]
