"""
Django settings for Auther_Manager project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'l%ka$qpdb20g738fuidp%!qw4pjfyr8rt)*e)fm0s5b%tcp@@1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'app_01',
    'app_02',
    'app_03',
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]

SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Auther_Manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Auther_Manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'op_oa_auth',
        'USER':'oaauth',
        'PASSWORD':'iXeL_604',
        'HOST':'op-oa-auth-mysql-writer',
        'PORT':'3306',
        'OPTIONS':{
              "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
          }
    },
    'auth_db':{
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ytkoa',
        'USER': 'ytkoaonline',
        'PASSWORD': 'ytkoaonline@ytk123',
        'HOST': 'op-servicedb-online',
        'PORT': '3306',
        'OPTIONS': {
              "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
          }
    },
    'auth_db_2':{
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bx_reimb',
        'USER': 'reimb',
        'PASSWORD': 'reimb',
        'HOST': 'op-servicedb-online',
        'PORT': '3306',
        'OPTIONS': {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    },
    'auth_db_3':{
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ytktb',
        'USER': 'tb',
        'PASSWORD': 'tb123fenbi',
        'HOST': 'op-servicedb-online',
        'PORT': '3306',
        'OPTIONS': {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}



DATABASES_APPS_MAPPING = {
    'app_01':'auth_db',
    'app_02':'auth_db_2',
    'app_03':'auth_db_3',
}

DATABASE_ROUTERS = ['app_01.database_app_router.DatabaseAppsRouter',
                    'app_02.database_app_router.DatabaseAppsRouter',
                    'app_03.database_app_router.DatabaseAppsRouter']

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'
USE_TZ = False

USE_I18N = True

USE_L10N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "/static/")