# Generated by Django 3.0.7 on 2020-07-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_02', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oaapprovergroup',
            options={'managed': False, 'verbose_name_plural': '审批组管理'},
        ),
        migrations.AlterModelOptions(
            name='oacondition',
            options={'managed': False, 'verbose_name_plural': '申请报销管理'},
        ),
        migrations.AlterModelOptions(
            name='oatransferring',
            options={'managed': False, 'verbose_name_plural': '审批流程管理'},
        ),
        migrations.AlterModelOptions(
            name='oaworkflow',
            options={'managed': False, 'verbose_name_plural': '工作流程管理'},
        ),
    ]
