# Generated by Django 3.0.7 on 2020-07-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_02', '0002_auto_20200717_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='OaAccountCoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('coding', models.CharField(max_length=200, verbose_name='对应代码')),
                ('remark', models.CharField(max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '费用代码管理',
                'db_table': 'oa_account_coding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OaBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(default='招商银行', max_length=30, verbose_name='银行名称')),
                ('bankaccount', models.CharField(max_length=100, verbose_name='银行账户')),
                ('useCompany', models.TextField(verbose_name='所属公司')),
                ('subject', models.CharField(blank=True, max_length=50, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '银行管理',
                'db_table': 'oa_bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OaFeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeName', models.CharField(max_length=100, verbose_name='费用名称')),
                ('subject', models.CharField(max_length=100, verbose_name='费用类型')),
                ('third', models.CharField(max_length=100, verbose_name='费用所属第三类型')),
                ('seeCompany', models.TextField(verbose_name='可查看的公司名')),
                ('seeDept', models.TextField(verbose_name='可查看的部门')),
                ('noDept', models.TextField()),
                ('specialPerson', models.TextField()),
                ('noPerson', models.TextField()),
                ('formids', models.CharField(max_length=100)),
                ('crashFlow', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '费用类型管理',
                'db_table': 'oa_fee_type',
                'managed': False,
            },
        ),
    ]
