# Generated by Django 3.0.7 on 2020-07-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap', models.CharField(max_length=50, unique=True, verbose_name='Ldap')),
                ('noter', models.IntegerField(default=0, verbose_name='Noter')),
                ('admin', models.IntegerField(default=0, verbose_name='Admin')),
            ],
            options={
                'verbose_name_plural': 'Permisson',
                'db_table': 'permission',
                'managed': False,
            },
        ),
    ]
