# Generated by Django 3.0.7 on 2020-07-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_03', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap', models.CharField(max_length=255, unique=True, verbose_name='Ldap')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('money', models.IntegerField(verbose_name='金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('company', models.CharField(default=None, max_length=20, verbose_name='公司')),
            ],
            options={
                'verbose_name_plural': 'TB内容管理',
                'db_table': 'tbs',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'managed': False, 'verbose_name_plural': 'TB权限管理'},
        ),
    ]
